name:                escape-the-room
version:             0.1.0.0
github:              "iu-haskell-fall-2020/escape-the-room"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "n.kudasov@innopolis.ru"
copyright:           "2020 Innopolis University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iu-haskell-fall-2020/escape-the-room#readme>

custom-setup:
  dependencies:
  - base
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- codeworld-api
- text

library:
  source-dirs: src

executables:
  escape-the-room-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-the-room

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-the-room
    - hspec
    - HUnit
    - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell
